image: elixir:latest

services:
  - postgres:latest

variables:
  POSTGRES_HOST: postgres
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: "postgres"
  MIX_ENV: "test"

before_script:
  - mix local.rebar --force
  - mix local.hex --force
  - mix deps.get --only test

code_quality:
  stage: test
  script:
    - mix format --check-formatted
    - mix credo --strict

test:
  stage: test
  script:
    - mix db.setup
    - mix test
